include theos/makefiles/common.mk

BUNDLE_NAME = CloudPrintSettings
CloudPrintSettings_FILES = 
CloudPrintSettings_INSTALL_PATH = /Library/PreferenceBundles/
CloudPrintSettings_FRAMEWORKS = UIKit
CloudPrintSettings_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
