include theos/makefiles/common.mk

CLASS_DIR = Submodule/AFOAuth2Client

SUBPROJECT_NAME = AFNetworking
AFNetworking_FILES = $(CLASS_DIR)/AFOAuth2Client.m 
AFNetworking_CFLAGS = -fobjc-arc -I$(CLASS_DIR) -I../AFNetworking/Submodule/AFNetworking/

include $(THEOS_MAKE_PATH)/subproject.mk
